"""initial

Revision ID: 3377af6bc304
Revises: 7ba8e831a0d3
Create Date: 2025-08-08 15:11:06.273729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3377af6bc304'
down_revision = '7ba8e831a0d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.drop_table('chatbot_response')
    op.drop_table('clinic')
    op.drop_table('appointment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointment',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('appointment_pkey'))
    )
    op.create_table('clinic',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('clinic_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='clinic_pkey'),
    sa.UniqueConstraint('email', name='clinic_email_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('chatbot_response',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('question', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('answer', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('clinic_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinic.id'], name=op.f('chatbot_response_clinic_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('chatbot_response_pkey'))
    )
    op.drop_table('user')
    # ### end Alembic commands ###
